version: '2.23.0-desktop.1'

services:
  server:
    build: ./server
    ports:
      - "80:5000"
    volumes:
      - ./server:/usr/app
    environment:
      - FLASK_ENV=development
    networks:
      - mynetwork

  web:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/spp
    depends_on:
      - server
    networks:
      - mynetwork

  python_env:
    image: python-env
    build:
      context: ./python-env
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    command: bash
    volumes:
      - .:/usr/src/app
    networks:
      - mynetwork

  cpp_env:
    image: cpp-env
    build:
      context: ./cpp-env
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    command: bash
    volumes:
      - .:/usr/src/app
    networks:
      - mynetwork

  java_env:
    image: java-env
    build:
      context: ./java-env
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    command: bash
    volumes:
      - .:/usr/src/app
    networks:
      - mynetwork

networks:
  mynetwork:
